/**
 * Core Verification Constants, Trust Levels, and Result Types for SecureWork Verify.
 * Principle: Evidence first, conclusion second.
 */

const TRUST_LEVELS = {
  LEVEL_0_UNKNOWN: 'LEVEL 0 UNKNOWN',
  LEVEL_1_SOURCE_FOUND: 'LEVEL 1 SOURCE_FOUND',
  LEVEL_2_SOURCE_VERIFIED: 'LEVEL 2 SOURCE_VERIFIED',
  LEVEL_3_INTEGRITY_VERIFIED: 'LEVEL 3 INTEGRITY_VERIFIED',
  LEVEL_4_SIGNATURE_VERIFIED: 'LEVEL 4 SIGNATURE_VERIFIED',
  LEVEL_5_CURRENTLY_VALID: 'LEVEL 5 CURRENTLY_VALID'
};

const RESULT_TYPES = {
  VERIFIED: 'VERIFIED',
  SOURCE_VERIFIED: 'SOURCE_VERIFIED',
  SOURCE_FOUND: 'SOURCE_FOUND',
  ALTERED: 'ALTERED',
  NOT_EXACT_FILE_MATCH: 'NOT_EXACT_FILE_MATCH',
  NOT_FOUND: 'NOT_FOUND',
  CREDENTIAL_REVOKED: 'CREDENTIAL_REVOKED',
  CREDENTIAL_EXPIRED: 'CREDENTIAL_EXPIRED',
  CREDENTIAL_SUPERSEDED: 'CREDENTIAL_SUPERSEDED',
  ISSUER_SUSPENDED: 'ISSUER_SUSPENDED',
  ISSUER_REVOKED: 'ISSUER_REVOKED',
  ISSUER_INACTIVE: 'ISSUER_INACTIVE',
  SIGNATURE_INVALID: 'SIGNATURE_INVALID',
  KEY_COMPROMISED: 'KEY_COMPROMISED',
  IDENTITY_MISMATCH: 'IDENTITY_MISMATCH',
  CONFLICTING_EVIDENCE: 'CONFLICTING_EVIDENCE',
  MANUAL_REVIEW: 'MANUAL_REVIEW',
  MANUALLY_VERIFIED: 'MANUALLY_VERIFIED',
  UNSUPPORTED_SOURCE: 'UNSUPPORTED_SOURCE',
  UNTRUSTED_ORIGIN: 'UNTRUSTED_ORIGIN'
};

const CHECK_NAMES = [
  'organizationTrust',
  'sourceTrust',
  'issuerAuthorization',
  'issuerKeyStatus',
  'documentIntegrity',
  'digitalSignature',
  'recipientBinding',
  'credentialStatus',
  'expiration',
  'revocation',
  'sourceEvidence',
  'ocrEvidence',
  'aiEvidence',
  'humanEvidence',
  'timestampEvidence',
  'conflicts'
];

module.exports = {
  TRUST_LEVELS,
  RESULT_TYPES,
  CHECK_NAMES
};
